require "json"

module XIVAPI
  module Structs
    # Struct for an attribute for a GearSet.
    # An Attribute corresponds to a stat, and has both a name and a value.
    struct GearSetAttribute
      # define a JSON mapping to create instances of this struct
      JSON.mapping(
        attribute: {type: Structs::IDName, key: "Attribute"},
        value: {type: UInt64, key: "Value"},
      )
      # An `IDName` struct containing the name and id of the attribute, e.g. Piety
      getter attribute
      # The value of the attribute generated by the Gear in the GearSet.
      getter value
    end
  end
end
