require "json"
require "../utils/id_name"

module XIVAPI
  module Dataclasses
    # Dataclass for an attribute for a GearSet.
    # An Attribute corresponds to a stat, and has both a name and a value.
    class GearSetAttribute
      include JSON::Serializable
      # An `IDName` class containing the name and id of the attribute, e.g. Piety
      @[JSON::Field(key: "Attribute")]
      getter attribute : IDName
      # The value of the attribute generated by the Gear in the GearSet.
      @[JSON::Field(key: "Value")]
      getter value : UInt64
    end
  end
end
