ENDPOINT_MAP = {
  "/lodestone"              => Structs::Lodestone,
  "/lodestone/news"         => Array(Structs::News),
  "/lodestone/notices"      => Array(Structs::Notice),
  "/lodestone/maintenance"  => Array(Structs::Status),
  "/lodestone/updates"      => Array(Structs::Notice),
  "/lodestone/status"       => Array(Structs::Status),
  "/lodestone/topics"       => Array(Structs::News),
  "/lodestone/worldstatus"  => Array(Structs::WorldStatus),
  "/lodestone/devblog"      => Array(Structs::Devblog),
  "/lodestone/devposts"     => Array(Structs::Devpost),
  "/lodestone/deepdungeon"  => Array(Structs::DeepDungeon),
  "/lodestone/heavenonhigh" => Array(Structs::DeepDungeon),
  "/lodestone/feasts"       => Array(Structs::Feast),
}
